import type { Mission, MissionMemberProfile } from "../types";

export const stubMissions: Mission[] = [
  {
    id: "mission-1",
    title: "Reduce Public Safety Vacancy Rate",
    description:
      "Address the critical 18% vacancy rate in Public Safety by accelerating recruitment, improving the onboarding pipeline, and mapping key skills to training programs.",
    status: "active",
    priority: "critical",
    progress: 25,
    sectorId: "public-safety",
    rewardPoints: 180,
    participantCount: 34,
    communityImpact: "Reduce emergency response staffing gaps across police, fire, and EMS teams before summer demand peaks.",
    tags: ["Recruitment", "Training", "Fast-track"],
    assignee: "J. Martinez",
    dueDate: "2026-04-30",
    steps: [
      {
        id: "m1-s1",
        order: 1,
        title: "Audit all open Public Safety roles",
        description: "Review all 47 unfilled roles and categorize by urgency and tenure requirements.",
        completed: true,
        dueDate: "2026-03-10",
      },
      {
        id: "m1-s2",
        order: 2,
        title: "Map required skills to available training",
        description: "Identify which emergency response and crisis management skills have no training program.",
        completed: false,
        dueDate: "2026-03-20",
      },
      {
        id: "m1-s3",
        order: 3,
        title: "Launch targeted recruitment campaign",
        description: "Post roles on 3 new job boards and partner with community colleges.",
        completed: false,
        dueDate: "2026-04-01",
      },
      {
        id: "m1-s4",
        order: 4,
        title: "Implement 30-day onboarding fast-track",
        description: "Compress onboarding from 60 days to 30 days using digital training modules.",
        completed: false,
        dueDate: "2026-04-15",
      },
    ],
    impactMetrics: [
      { label: "Open Roles Filled", before: 0, after: 12, unit: "roles" },
      { label: "Avg Time to Fill", before: 45, after: 30, unit: "days" },
      { label: "Training Coverage", before: 42, after: 75, unit: "%" },
    ],
  },
  {
    id: "mission-2",
    title: "Upskill Healthcare IT Staff",
    description:
      "Build internal capacity in Health Informatics and medical coding to reduce external contractor dependency by 40%.",
    status: "active",
    priority: "watch",
    progress: 67,
    sectorId: "healthcare",
    rewardPoints: 140,
    participantCount: 21,
    communityImpact: "Build local healthcare tech capacity so residents get faster coding, intake, and records support.",
    tags: ["Upskilling", "Certification", "Healthcare IT"],
    assignee: "L. Thompson",
    dueDate: "2026-03-31",
    steps: [
      {
        id: "m2-s1",
        order: 1,
        title: "Identify 20 eligible staff for ICD-10 certification",
        description: "Survey healthcare staff for interest and existing competencies in medical coding.",
        completed: true,
        dueDate: "2026-02-15",
      },
      {
        id: "m2-s2",
        order: 2,
        title: "Enroll staff in AAPC CPC certification prep",
        description: "Coordinate with HR to fund and schedule the 4-week course.",
        completed: true,
        dueDate: "2026-03-01",
      },
      {
        id: "m2-s3",
        order: 3,
        title: "Validate competency and assign new roles",
        description: "Administer certification exam, celebrate completions, and update job profiles.",
        completed: false,
        dueDate: "2026-03-31",
      },
    ],
    impactMetrics: [
      { label: "Staff Certified", before: 3, after: 20, unit: "people" },
      { label: "Contractor Cost", before: 85000, after: 51000, unit: "$" },
      { label: "Internal Coverage Rate", before: 28, after: 68, unit: "%" },
    ],
  },
  {
    id: "mission-3",
    title: "Logistics Driver Recruitment Sprint",
    description:
      "Close the critical 67-role gap in Logistics Coordinator positions before Q2 peak shipping season.",
    status: "active",
    priority: "critical",
    progress: 50,
    sectorId: "logistics",
    rewardPoints: 220,
    participantCount: 43,
    communityImpact: "Stabilize freight and municipal logistics staffing ahead of peak shipping season and service demand.",
    tags: ["Hiring Sprint", "CDL", "HazMat"],
    assignee: "R. Davis",
    dueDate: "2026-04-15",
    steps: [
      {
        id: "m3-s1",
        order: 1,
        title: "Partner with 5 trucking schools",
        description: "Establish pipeline agreements with regional CDL training programs.",
        completed: true,
        dueDate: "2026-02-28",
      },
      {
        id: "m3-s2",
        order: 2,
        title: "Create hazmat handling fast-track certification",
        description: "Develop 2-week internal HazMat handling course for licensed drivers.",
        completed: true,
        dueDate: "2026-03-15",
      },
      {
        id: "m3-s3",
        order: 3,
        title: "Host 3 virtual job fairs",
        description: "Recruit at regional CDL events and transportation industry job fairs.",
        completed: false,
        dueDate: "2026-03-30",
      },
      {
        id: "m3-s4",
        order: 4,
        title: "Process and onboard 40+ hires",
        description: "Complete background checks, licensing verification, and onboarding in 2 weeks.",
        completed: false,
        dueDate: "2026-04-15",
      },
    ],
    impactMetrics: [
      { label: "Roles Filled", before: 0, after: 40, unit: "roles" },
      { label: "Attrition Rate", before: 22, after: 12, unit: "%" },
      { label: "HazMat Certified Drivers", before: 15, after: 55, unit: "people" },
    ],
  },
  {
    id: "mission-4",
    title: "Technology Talent Pipeline",
    description: "Establish a 6-month rolling pipeline for cloud and cybersecurity talent through university partnerships.",
    status: "active",
    priority: "watch",
    progress: 33,
    sectorId: "technology",
    rewardPoints: 160,
    participantCount: 18,
    communityImpact: "Grow a reliable local cloud and cybersecurity pipeline instead of competing for the same external talent pool.",
    tags: ["Pipeline", "Internships", "Cybersecurity"],
    assignee: "S. Patel",
    dueDate: "2026-06-30",
    steps: [
      {
        id: "m4-s1",
        order: 1,
        title: "Identify 3 partner universities",
        description: "Target CS and cybersecurity programs at regional universities.",
        completed: true,
        dueDate: "2026-02-01",
      },
      {
        id: "m4-s2",
        order: 2,
        title: "Launch internship program",
        description: "Offer 10 paid internships for summer 2026 in cloud and security.",
        completed: false,
        dueDate: "2026-04-01",
      },
      {
        id: "m4-s3",
        order: 3,
        title: "Convert top interns to full-time offers",
        description: "Evaluate and extend offers to 6 of the 10 interns.",
        completed: false,
        dueDate: "2026-08-01",
      },
    ],
    impactMetrics: [
      { label: "Pipeline Candidates", before: 4, after: 25, unit: "people" },
      { label: "Avg Time to Fill (Tech)", before: 80, after: 55, unit: "days" },
    ],
  },
  {
    id: "mission-5",
    title: "Retail Seasonal Workforce Prep",
    description: "Prepare a 150-person seasonal surge workforce for Q4 retail peak season.",
    status: "active",
    priority: "stable",
    progress: 0,
    sectorId: "retail",
    rewardPoints: 95,
    participantCount: 12,
    communityImpact: "Prepare neighborhood retail employers for seasonal demand without last-minute labor shortages.",
    tags: ["Seasonal", "Onboarding", "Retail Ops"],
    assignee: undefined,
    dueDate: "2026-10-01",
    steps: [
      {
        id: "m5-s1",
        order: 1,
        title: "Define seasonal role requirements",
        description: "Determine headcount needs per store location and role type.",
        completed: false,
        dueDate: "2026-07-01",
      },
      {
        id: "m5-s2",
        order: 2,
        title: "Launch early applications campaign",
        description: "Post seasonal roles in July to beat competitor postings.",
        completed: false,
        dueDate: "2026-08-01",
      },
      {
        id: "m5-s3",
        order: 3,
        title: "Complete onboarding and training",
        description: "Onboard all seasonal staff with 1-week orientation program.",
        completed: false,
        dueDate: "2026-10-01",
      },
    ],
    impactMetrics: [
      { label: "Seasonal Staff Hired", before: 0, after: 150, unit: "people" },
      { label: "Onboarding Time", before: 14, after: 7, unit: "days" },
    ],
  },
  {
    id: "mission-6",
    title: "Close Construction Skills Gap",
    description: "Map and close the 8 unmapped high-demand skills in construction through targeted training partnerships.",
    status: "paused",
    priority: "watch",
    progress: 50,
    sectorId: "construction",
    rewardPoints: 150,
    participantCount: 17,
    communityImpact: "Close critical construction skill gaps so capital projects do not stall on certification bottlenecks.",
    tags: ["Skills Mapping", "Training Providers", "Construction"],
    assignee: "K. Williams",
    dueDate: "2026-05-31",
    steps: [
      {
        id: "m6-s1",
        order: 1,
        title: "Audit 8 unmapped construction skills",
        description: "Review demand data and identify highest-priority skills to address first.",
        completed: true,
        dueDate: "2026-02-15",
      },
      {
        id: "m6-s2",
        order: 2,
        title: "Identify training providers",
        description: "Source certified OSHA and civil engineering training programs.",
        completed: true,
        dueDate: "2026-03-01",
      },
      {
        id: "m6-s3",
        order: 3,
        title: "Negotiate training contracts",
        description: "Finalize agreements with 2 training providers. (Currently paused — budget approval pending.)",
        completed: false,
        dueDate: "2026-04-15",
      },
      {
        id: "m6-s4",
        order: 4,
        title: "Enroll 50 workers in training programs",
        description: "Coordinate enrollment and track completion rates.",
        completed: false,
        dueDate: "2026-05-31",
      },
    ],
    impactMetrics: [
      { label: "Unmapped Skills", before: 8, after: 2, unit: "skills" },
      { label: "Training Enrollment", before: 0, after: 50, unit: "workers" },
    ],
  },
  {
    id: "mission-7",
    title: "Finance Succession Planning",
    description: "Identify and develop 5 high-potential finance professionals to fill senior roles within 18 months.",
    status: "completed",
    priority: "stable",
    progress: 100,
    sectorId: "finance",
    rewardPoints: 130,
    participantCount: 9,
    communityImpact: "Protect continuity in finance operations by building bench strength for senior public-sector roles.",
    tags: ["Succession", "Mentorship", "Leadership"],
    assignee: "A. Johnson",
    dueDate: "2026-01-31",
    steps: [
      {
        id: "m7-s1",
        order: 1,
        title: "Identify succession candidates",
        description: "Use performance data to select top 10 candidates.",
        completed: true,
        dueDate: "2025-10-01",
      },
      {
        id: "m7-s2",
        order: 2,
        title: "Launch development program",
        description: "Pair candidates with senior mentors and assign stretch projects.",
        completed: true,
        dueDate: "2025-11-01",
      },
      {
        id: "m7-s3",
        order: 3,
        title: "Finalize succession map",
        description: "Document readiness ratings and create role coverage plan.",
        completed: true,
        dueDate: "2026-01-31",
      },
    ],
    impactMetrics: [
      { label: "Succession Candidates Identified", before: 0, after: 5, unit: "people" },
      { label: "Senior Role Coverage", before: 60, after: 92, unit: "%" },
    ],
  },
  {
    id: "mission-8",
    title: "Education Instructor Retention",
    description: "Reduce instructor attrition from 16% to under 8% through compensation review and professional development.",
    status: "completed",
    priority: "watch",
    progress: 100,
    sectorId: "education",
    rewardPoints: 145,
    participantCount: 26,
    communityImpact: "Keep more instructors in classrooms through stronger compensation signals and career development support.",
    tags: ["Retention", "Compensation", "Professional Development"],
    assignee: "M. Chen",
    dueDate: "2026-02-28",
    steps: [
      {
        id: "m8-s1",
        order: 1,
        title: "Conduct instructor satisfaction survey",
        description: "Survey all 1,200 instructors on compensation, workload, and growth.",
        completed: true,
        dueDate: "2025-12-01",
      },
      {
        id: "m8-s2",
        order: 2,
        title: "Benchmark compensation against market",
        description: "Compare salaries to regional and national benchmarks.",
        completed: true,
        dueDate: "2026-01-01",
      },
      {
        id: "m8-s3",
        order: 3,
        title: "Implement retention bonuses and development budget",
        description: "Roll out $2,000 annual professional development stipend.",
        completed: true,
        dueDate: "2026-02-15",
      },
      {
        id: "m8-s4",
        order: 4,
        title: "Measure 30-day attrition impact",
        description: "Compare voluntary departure rates to baseline.",
        completed: true,
        dueDate: "2026-02-28",
      },
    ],
    impactMetrics: [
      { label: "Instructor Attrition Rate", before: 16, after: 7, unit: "%" },
      { label: "Satisfaction Score", before: 61, after: 82, unit: "/100" },
    ],
  },
];

export const stubMissionMemberProfile: MissionMemberProfile = {
  id: "member-city-admin",
  name: "City Admin",
  role: "Community Workforce Lead",
  city: "Montgomery, AL",
  level: 4,
  points: 820,
  nextLevelPoints: 1000,
  streak: 6,
  missionPoints: 540,
  skillPoints: 120,
  sectorPoints: 80,
  playbookPoints: 80,
  completedMissionCount: 2,
  activeMissionCount: 5,
  contributedSteps: 11,
  helpedWorkers: 148,
  playbooksCreated: 1,
  playbooksLiked: 3,
  playbooksSaved: 4,
  skillActionsCompleted: 5,
  sectorActionsCompleted: 3,
  badges: [
    {
      id: "systems-builder",
      label: "Systems Builder",
      description: "Created repeatable workforce interventions across multiple sectors.",
    },
    {
      id: "field-connector",
      label: "Field Connector",
      description: "Linked community partners and training pathways to live hiring demand.",
    },
    {
      id: "streak-runner",
      label: "Streak Runner",
      description: "Stayed active in mission delivery for six consecutive cycles.",
    },
  ],
};
