import type { Playbook } from "../types";

export const stubPlaybooks: Playbook[] = [
  {
    id: "playbook-1",
    title: "Emergency Services Rapid Onboarding",
    summary:
      "A 30-day accelerated onboarding program for paramedics and emergency dispatchers designed to cut time-to-productivity in half without sacrificing safety compliance.",
    authorName: "J. Martinez",
    authorAvatar: "/avatars/user-1.png",
    sectorId: "public-safety",
    tags: ["Onboarding", "Public Safety", "EMT", "Training"],
    likes: 142,
    saves: 67,
    createdAt: "2026-02-10T09:00:00Z",
    rewardPoints: 26,
    estimatedHours: 12,
    difficulty: "operator",
    impactSummary: "Helps departments shorten the gap between offer acceptance and field readiness for emergency hires.",
    linkedSkills: ["Crisis Management", "Incident Command", "Emergency Response"],
    hasLiked: false,
    hasSaved: true,
    steps: [
      { order: 1, instruction: "Audit current onboarding timeline and identify bottlenecks." },
      { order: 2, instruction: "Convert paper-based training to digital modules via LMS." },
      { order: 3, instruction: "Schedule weekly check-ins between new hire and supervisor for first 30 days." },
      { order: 4, instruction: "Review competency assessments at Day 15 and Day 30." },
    ],
  },
  {
    id: "playbook-2",
    title: "ICU Nurse Retention Strategy",
    summary:
      "Evidence-based tactics to reduce ICU nurse turnover below 10%, including flexible scheduling, mental health resources, and career ladder programs.",
    authorName: "L. Thompson",
    authorAvatar: "/avatars/user-2.png",
    sectorId: "healthcare",
    tags: ["Retention", "Healthcare", "Nursing", "Wellbeing"],
    likes: 98,
    saves: 44,
    createdAt: "2026-01-22T14:30:00Z",
    rewardPoints: 22,
    estimatedHours: 10,
    difficulty: "advanced",
    impactSummary: "Targets burnout drivers and keeps ICU staffing stable in one of the city's most fragile care environments.",
    linkedSkills: ["Leadership", "Healthcare Operations", "Workforce Planning"],
    hasLiked: true,
    hasSaved: false,
    steps: [
      { order: 1, instruction: "Survey ICU nurses on burnout drivers and scheduling preferences." },
      { order: 2, instruction: "Implement 3-shift rotation with self-scheduling platform." },
      { order: 3, instruction: "Launch peer support and EAP program with dedicated mental health budget." },
      { order: 4, instruction: "Define clinical ladder with clear promotion criteria and salary bands." },
    ],
  },
  {
    id: "playbook-3",
    title: "Cloud Team Scaling Playbook",
    summary:
      "How to scale a cloud engineering team from 5 to 20 in 6 months — sourcing strategy, interview process, and onboarding runway for AWS architects.",
    authorName: "S. Patel",
    authorAvatar: "/avatars/user-3.png",
    sectorId: "technology",
    tags: ["Recruiting", "Technology", "Cloud", "Scaling"],
    likes: 87,
    saves: 39,
    createdAt: "2026-01-15T10:00:00Z",
    rewardPoints: 20,
    estimatedHours: 8,
    difficulty: "advanced",
    impactSummary: "Gives tech teams a repeatable way to scale cloud hiring while preserving quality and onboarding capacity.",
    linkedSkills: ["Cloud Infrastructure", "Software Development", "Leadership"],
    hasLiked: false,
    hasSaved: false,
    steps: [
      { order: 1, instruction: "Define the target architecture team structure and role levels." },
      { order: 2, instruction: "Post on specialized tech job boards (Built In, Levels.fyi, LinkedIn)." },
      { order: 3, instruction: "Run structured technical interviews with a defined rubric (no whiteboarding)." },
    ],
  },
  {
    id: "playbook-4",
    title: "Reducing Driver Turnover",
    summary:
      "A comprehensive retention program for logistics coordinators and CDL drivers, addressing the top 5 reasons for voluntary attrition in transportation.",
    authorName: "R. Davis",
    authorAvatar: "/avatars/user-4.png",
    sectorId: "logistics",
    tags: ["Retention", "Logistics", "CDL", "Compensation"],
    likes: 74,
    saves: 31,
    createdAt: "2026-02-01T08:00:00Z",
    rewardPoints: 24,
    estimatedHours: 9,
    difficulty: "operator",
    impactSummary: "Reduces transportation attrition by aligning pay, comfort, and route expectations with actual driver needs.",
    linkedSkills: ["Operations", "Safety Compliance", "Leadership"],
    hasLiked: false,
    hasSaved: true,
    steps: [
      { order: 1, instruction: "Conduct exit interviews for last 50 voluntary departures — extract top themes." },
      { order: 2, instruction: "Benchmark CDL driver pay against region and top competitors." },
      { order: 3, instruction: "Introduce mileage-based performance bonus and quarterly retention bonus." },
      { order: 4, instruction: "Invest in cab comfort upgrades and home-time scheduling improvements." },
    ],
  },
  {
    id: "playbook-5",
    title: "Teacher Mentorship Program",
    summary:
      "Pair new instructors with experienced mentors during their first year to reduce early attrition and accelerate classroom performance.",
    authorName: "M. Chen",
    authorAvatar: "/avatars/user-5.png",
    sectorId: "education",
    tags: ["Mentorship", "Education", "Retention", "New Hire"],
    likes: 56,
    saves: 28,
    createdAt: "2026-01-05T11:00:00Z",
    rewardPoints: 18,
    estimatedHours: 6,
    difficulty: "starter",
    impactSummary: "Supports early instructor success through structured mentoring and lower first-year attrition risk.",
    linkedSkills: ["Leadership", "Operations", "Education Delivery"],
    hasLiked: false,
    hasSaved: false,
    steps: [
      { order: 1, instruction: "Identify 30 senior instructors willing to serve as mentors." },
      { order: 2, instruction: "Match new hires 1:1 with mentors based on subject area and school level." },
      { order: 3, instruction: "Schedule bi-weekly check-ins for the first semester." },
    ],
  },
  {
    id: "playbook-6",
    title: "Construction Safety Orientation",
    summary:
      "A 5-day mandatory safety orientation for all new construction hires covering OSHA compliance, HazMat protocols, and site-specific procedures.",
    authorName: "K. Williams",
    authorAvatar: "/avatars/user-6.png",
    sectorId: "construction",
    tags: ["Safety", "Construction", "OSHA", "Onboarding"],
    likes: 63,
    saves: 25,
    createdAt: "2025-12-18T09:30:00Z",
    rewardPoints: 19,
    estimatedHours: 7,
    difficulty: "operator",
    impactSummary: "Creates a standard safety baseline for construction crews before they step into high-risk sites.",
    linkedSkills: ["Safety Compliance", "Operations", "HazMat"],
    hasLiked: true,
    hasSaved: true,
    steps: [
      { order: 1, instruction: "Day 1: OSHA 10-hour general industry overview." },
      { order: 2, instruction: "Day 2: Site-specific hazard identification and PPE fitting." },
      { order: 3, instruction: "Day 3: HazMat awareness and emergency response procedures." },
      { order: 4, instruction: "Day 4–5: Practical assessments and competency sign-off." },
    ],
  },
  {
    id: "playbook-7",
    title: "Finance Graduate Hire Program",
    summary:
      "A structured 2-year rotational program for finance graduates covering risk, compliance, and investment operations — building the next generation of analysts.",
    authorName: "A. Johnson",
    authorAvatar: "/avatars/user-7.png",
    sectorId: "finance",
    tags: ["Graduate Program", "Finance", "Rotational", "Talent Pipeline"],
    likes: 41,
    saves: 18,
    createdAt: "2026-01-28T15:00:00Z",
    rewardPoints: 17,
    estimatedHours: 8,
    difficulty: "advanced",
    impactSummary: "Builds a long-term finance bench through structured rotations rather than one-off analyst hiring.",
    linkedSkills: ["Leadership", "Data Analysis", "Operations"],
    hasLiked: false,
    hasSaved: false,
    steps: [
      { order: 1, instruction: "Partner with 5 target universities for on-campus recruitment." },
      { order: 2, instruction: "Run structured case interview process with defined scoring rubric." },
      { order: 3, instruction: "Assign cohort to 4 six-month rotations across risk, compliance, trading, and ops." },
    ],
  },
  {
    id: "playbook-8",
    title: "Retail Peak Season Staffing",
    summary:
      "A repeatable framework for hiring, training, and managing 150+ seasonal retail associates in under 8 weeks for Q4 peak demand.",
    authorName: "B. Rivera",
    authorAvatar: "/avatars/user-8.png",
    sectorId: "retail",
    tags: ["Seasonal", "Retail", "High-Volume Hiring", "Q4"],
    likes: 38,
    saves: 15,
    createdAt: "2026-02-14T13:00:00Z",
    rewardPoints: 16,
    estimatedHours: 5,
    difficulty: "starter",
    impactSummary: "Makes high-volume seasonal hiring repeatable without overwhelming store managers or trainers.",
    linkedSkills: ["Operations", "Customer Service", "Leadership"],
    hasLiked: false,
    hasSaved: false,
    steps: [
      { order: 1, instruction: "Open applications 90 days before peak start date." },
      { order: 2, instruction: "Use group interview sessions to screen 20 candidates at once." },
      { order: 3, instruction: "Deliver 1-week online pre-boarding before first shift." },
      { order: 4, instruction: "Assign buddy pairing for first 2 weeks on the floor." },
    ],
  },
  {
    id: "playbook-9",
    title: "Healthcare IT Upskilling Path",
    summary:
      "A 90-day cohort-based upskilling program to convert clinical staff into health informatics analysts without external hiring.",
    authorName: "L. Thompson",
    authorAvatar: "/avatars/user-2.png",
    sectorId: "healthcare",
    tags: ["Upskilling", "Healthcare IT", "Reskilling", "Certification"],
    likes: 29,
    saves: 12,
    createdAt: "2026-02-20T10:00:00Z",
    rewardPoints: 21,
    estimatedHours: 11,
    difficulty: "advanced",
    impactSummary: "Creates a path for clinical workers to move into informatics and reduce dependency on external contractors.",
    linkedSkills: ["Healthcare", "Data Science", "Cloud Infrastructure"],
    hasLiked: false,
    hasSaved: false,
    steps: [
      { order: 1, instruction: "Identify 15–20 clinical staff with aptitude and interest in IT." },
      { order: 2, instruction: "Enroll in AHIMA CDI and AAPC CPC programs simultaneously." },
      { order: 3, instruction: "Provide 4 hours/week release time for study during work hours." },
    ],
  },
  {
    id: "playbook-10",
    title: "Logistics Automation Transition",
    summary:
      "Prepare warehouse staff for automation adoption — reskilling 80% of manual pickers into automation supervisors and system operators.",
    authorName: "R. Davis",
    authorAvatar: "/avatars/user-4.png",
    sectorId: "logistics",
    tags: ["Automation", "Reskilling", "Logistics", "Future of Work"],
    likes: 21,
    saves: 8,
    createdAt: "2026-03-01T09:00:00Z",
    rewardPoints: 23,
    estimatedHours: 10,
    difficulty: "advanced",
    impactSummary: "Prepares frontline warehouse teams for automation while protecting retention and wage growth.",
    linkedSkills: ["Operations", "Software Development", "Safety Compliance"],
    hasLiked: false,
    hasSaved: false,
    steps: [
      { order: 1, instruction: "Map current manual roles to automation-adjacent supervision roles." },
      { order: 2, instruction: "Partner with robotics vendor for 3-day hands-on operator training." },
      { order: 3, instruction: "Run 6-week transition program with on-the-job automation mentoring." },
      { order: 4, instruction: "Retention guarantee: all completing the program receive immediate pay grade increase." },
    ],
  },
];
