export const missionsSeed = [
  // ========== PUBLIC SAFETY MISSIONS ==========
  {
    id: 'mission-ps-001',
    title: 'Public Safety Recruitment Surge 2026',
    description: 'Address critical staffing shortages across Montgomery police, fire, and EMS departments. Target 50 hires across patrol officers, firefighters, and paramedics before Q2 peak demand.',
    status: 'active',
    priority: 'critical',
    progress: 35,
    sectorId: 'public-safety',
    rewardPoints: 250,
    participantCount: 47,
    communityImpact: 'Faster emergency response times across all Montgomery neighborhoods, especially in West Montgomery and Midtown where response times currently exceed targets.',
    tags: ['Recruitment', 'Public Safety', 'Emergency Services', 'Fast-track'],
    assignee: 'Chief J. Martinez',
    dueDate: new Date('2026-05-31'),
    steps: [
      {
        id: 'ps001-s1',
        order: 1,
        title: 'Launch multi-channel recruitment campaign',
        description: 'Post open roles on Indeed, JobAps, USAJOBS, and local radio. Target veterans and career-changers.',
        completed: true,
        dueDate: new Date('2026-03-15'),
      },
      {
        id: 'ps001-s2',
        order: 2,
        title: 'Host public safety career fair',
        description: 'Partner with Alabama State University and local community centers for career fair in Downtown Montgomery.',
        completed: true,
        dueDate: new Date('2026-03-25'),
      },
      {
        id: 'ps001-s3',
        order: 3,
        title: 'Streamline hiring process',
        description: 'Reduce time from application to offer from 90 days to 45 days through parallel background checks and physicals.',
        completed: false,
        dueDate: new Date('2026-04-15'),
      },
      {
        id: 'ps001-s4',
        order: 4,
        title: 'Launch accelerated academy for EMTs',
        description: 'Partner with H. Councill Trenholm State for 6-week EMT bootcamp with direct hiring pipeline.',
        completed: false,
        dueDate: new Date('2026-05-15'),
      },
    ],
    impactMetrics: [
      { label: 'Open Roles Filled', before: 0, after: 18, unit: 'positions' },
      { label: 'Avg Time to Hire', before: 90, after: 52, unit: 'days' },
      { label: 'Application Volume', before: 145, after: 312, unit: 'applicants' },
    ],
  },

  {
    id: 'mission-ps-002',
    title: 'Crisis Intervention Training Expansion',
    description: 'Train 100% of patrol officers in Crisis Intervention Team (CIT) protocols to improve mental health crisis response across Montgomery.',
    status: 'active',
    priority: 'watch',
    progress: 58,
    sectorId: 'public-safety',
    rewardPoints: 160,
    participantCount: 23,
    communityImpact: 'Better outcomes for mental health crisis calls, reducing use of force incidents and connecting residents to community resources.',
    tags: ['Training', 'Mental Health', 'Community Safety', 'De-escalation'],
    assignee: 'Lt. K. Williams',
    dueDate: new Date('2026-06-30'),
    steps: [
      {
        id: 'ps002-s1',
        order: 1,
        title: 'Partner with local mental health providers',
        description: 'Establish MOU with Montgomery Area Mental Health Authority for curriculum development.',
        completed: true,
        dueDate: new Date('2026-03-01'),
      },
      {
        id: 'ps002-s2',
        order: 2,
        title: 'Certify 20 CIT instructors',
        description: 'Send officers to Memphis Model CIT training for train-the-trainer certification.',
        completed: true,
        dueDate: new Date('2026-03-20'),
      },
      {
        id: 'ps002-s3',
        order: 3,
        title: 'Run first 4 training cohorts',
        description: 'Complete CIT training for 80 patrol officers (4 cohorts of 20).',
        completed: false,
        dueDate: new Date('2026-05-30'),
      },
      {
        id: 'ps002-s4',
        order: 4,
        title: 'Establish mobile crisis response team',
        description: 'Launch co-responder model pairing officers with mental health clinicians.',
        completed: false,
        dueDate: new Date('2026-06-30'),
      },
    ],
    impactMetrics: [
      { label: 'Officers Trained', before: 42, after: 140, unit: 'officers' },
      { label: 'Use of Force in MH Calls', before: 18, after: 5, unit: 'incidents' },
      { label: 'MH Resource Connections', before: 23, after: 67, unit: 'referrals/month' },
    ],
  },

  // ========== HEALTHCARE MISSIONS ==========
  {
    id: 'mission-hc-001',
    title: 'Close the Nursing Gap at Baptist Health',
    description: 'Fill 35 RN and LPN vacancies across ICU, ED, and Med-Surg units through accelerated hiring and retention bonuses.',
    status: 'active',
    priority: 'critical',
    progress: 42,
    sectorId: 'healthcare',
    rewardPoints: 220,
    participantCount: 31,
    communityImpact: 'Reduce patient wait times and improve nurse-to-patient ratios, leading to better health outcomes for Montgomery residents.',
    tags: ['Nursing', 'Healthcare', 'Hiring Sprint', 'Retention'],
    assignee: 'Dr. L. Thompson',
    dueDate: new Date('2026-04-30'),
    steps: [
      {
        id: 'hc001-s1',
        order: 1,
        title: 'Launch signing bonus program',
        description: 'Offer $5,000 signing bonus for RNs and $3,000 for LPNs with 2-year commitment.',
        completed: true,
        dueDate: new Date('2026-03-10'),
      },
      {
        id: 'hc001-s2',
        order: 2,
        title: 'Partner with nursing schools',
        description: 'Create direct hiring pipeline with Auburn University Montgomery and Fortis College nursing programs.',
        completed: true,
        dueDate: new Date('2026-03-20'),
      },
      {
        id: 'hc001-s3',
        order: 3,
        title: 'Implement nurse residency program',
        description: 'Launch 12-week residency for new graduate nurses with mentorship and specialty rotations.',
        completed: false,
        dueDate: new Date('2026-04-15'),
      },
      {
        id: 'hc001-s4',
        order: 4,
        title: 'Recruit from out-of-state',
        description: 'Post on national nursing job boards and offer relocation assistance up to $4,000.',
        completed: false,
        dueDate: new Date('2026-04-30'),
      },
    ],
    impactMetrics: [
      { label: 'Nursing Vacancies', before: 35, after: 8, unit: 'open positions' },
      { label: 'Nurse-Patient Ratio (Med-Surg)', before: 6.2, after: 4.8, unit: 'patients per nurse' },
      { label: 'ED Wait Time', before: 82, after: 54, unit: 'minutes' },
    ],
  },

  {
    id: 'mission-hc-002',
    title: 'Medical Coding Certification Program',
    description: 'Upskill 25 healthcare administrative staff in medical coding (CPC certification) to reduce reliance on external contractors and improve billing accuracy.',
    status: 'active',
    priority: 'watch',
    progress: 68,
    sectorId: 'healthcare',
    rewardPoints: 145,
    participantCount: 28,
    communityImpact: 'Faster insurance claims processing and improved revenue cycle, allowing hospitals to reinvest in community health programs.',
    tags: ['Upskilling', 'Medical Coding', 'Certification', 'Healthcare IT'],
    assignee: 'M. Garcia, Revenue Cycle Director',
    dueDate: new Date('2026-05-15'),
    steps: [
      {
        id: 'hc002-s1',
        order: 1,
        title: 'Identify candidates from existing staff',
        description: 'Screen billing and admin staff for interest and aptitude in medical coding.',
        completed: true,
        dueDate: new Date('2026-02-28'),
      },
      {
        id: 'hc002-s2',
        order: 2,
        title: 'Enroll in AAPC CPC prep course',
        description: 'Fund online CPC certification prep for 30 staff (5 alternates in case of dropouts).',
        completed: true,
        dueDate: new Date('2026-03-15'),
      },
      {
        id: 'hc002-s3',
        order: 3,
        title: 'Provide exam fee and study support',
        description: 'Cover $450 exam fee and offer weekly study groups with senior coders.',
        completed: true,
        dueDate: new Date('2026-04-30'),
      },
      {
        id: 'hc002-s4',
        order: 4,
        title: 'Track certification success rate',
        description: 'Achieve 80% pass rate and promote certified coders to Coder II roles.',
        completed: false,
        dueDate: new Date('2026-05-15'),
      },
    ],
    impactMetrics: [
      { label: 'Staff Certified', before: 3, after: 22, unit: 'certified coders' },
      { label: 'Coding Contractor Costs', before: 95000, after: 38000, unit: '$/year' },
      { label: 'Claims Denial Rate', before: 12.4, after: 7.2, unit: '%' },
    ],
  },

  // ========== TECHNOLOGY MISSIONS ==========
  {
    id: 'mission-tech-001',
    title: 'Build Montgomery Cyber Defense Team',
    description: 'Hire and train 12 cybersecurity professionals to protect city infrastructure, utilities, and hospital networks from ransomware and cyber threats.',
    status: 'active',
    priority: 'critical',
    progress: 25,
    sectorId: 'technology',
    rewardPoints: 200,
    participantCount: 19,
    communityImpact: 'Protect critical infrastructure including water, power, and emergency dispatch systems from cyber attacks that could disrupt essential services.',
    tags: ['Cybersecurity', 'Technology', 'Infrastructure', 'Hiring'],
    assignee: 'S. Patel, CIO',
    dueDate: new Date('2026-07-31'),
    steps: [
      {
        id: 'tech001-s1',
        order: 1,
        title: 'Define cybersecurity roles and levels',
        description: 'Create job descriptions for SOC Analyst I/II, Incident Responder, and Security Engineer roles.',
        completed: true,
        dueDate: new Date('2026-03-10'),
      },
      {
        id: 'tech001-s2',
        order: 2,
        title: 'Partner with Alabama State CS program',
        description: 'Establish internship-to-hire pipeline for cybersecurity students.',
        completed: false,
        dueDate: new Date('2026-04-15'),
      },
      {
        id: 'tech001-s3',
        order: 3,
        title: 'Offer Security+ certification training',
        description: 'Fund CompTIA Security+ training and exam for 15 candidates transitioning from IT support.',
        completed: false,
        dueDate: new Date('2026-05-30'),
      },
      {
        id: 'tech001-s4',
        order: 4,
        title: 'Launch bug bounty and CTF challenges',
        description: 'Host Capture the Flag event to identify local cybersecurity talent.',
        completed: false,
        dueDate: new Date('2026-06-30'),
      },
    ],
    impactMetrics: [
      { label: 'Cyber Team Headcount', before: 2, after: 14, unit: 'staff' },
      { label: 'Security Incidents Detected', before: 12, after: 47, unit: 'incidents/month' },
      { label: 'Threat Response Time', before: 18, after: 4, unit: 'hours' },
    ],
  },

  {
    id: 'mission-tech-002',
    title: 'Modern Cloud Infrastructure Training',
    description: 'Upskill 20 city IT staff in AWS cloud services to support migration of legacy systems to the cloud.',
    status: 'active',
    priority: 'watch',
    progress: 55,
    sectorId: 'technology',
    rewardPoints: 130,
    participantCount: 22,
    communityImpact: 'Reduce IT infrastructure costs and improve service reliability for residents accessing city services online.',
    tags: ['Cloud', 'AWS', 'Upskilling', 'Infrastructure'],
    assignee: 'T. Brown, IT Director',
    dueDate: new Date('2026-06-15'),
    steps: [
      {
        id: 'tech002-s1',
        order: 1,
        title: 'Select training cohort',
        description: 'Identify 20 IT staff from infrastructure, helpdesk, and development teams.',
        completed: true,
        dueDate: new Date('2026-02-28'),
      },
      {
        id: 'tech002-s2',
        order: 2,
        title: 'Enroll in AWS Solutions Architect track',
        description: 'Provide access to AWS Skill Builder and live training workshops.',
        completed: true,
        dueDate: new Date('2026-03-20'),
      },
      {
        id: 'tech002-s3',
        order: 3,
        title: 'Build cloud migration pilot project',
        description: 'Migrate city permits database to AWS as hands-on learning project.',
        completed: false,
        dueDate: new Date('2026-05-15'),
      },
      {
        id: 'tech002-s4',
        order: 4,
        title: 'Achieve AWS certifications',
        description: 'Target 15 staff to earn AWS Certified Solutions Architect - Associate.',
        completed: false,
        dueDate: new Date('2026-06-15'),
      },
    ],
    impactMetrics: [
      { label: 'Cloud-Certified Staff', before: 2, after: 17, unit: 'certifications' },
      { label: 'Infrastructure Costs', before: 145000, after: 98000, unit: '$/year' },
      { label: 'System Uptime', before: 97.2, after: 99.6, unit: '%' },
    ],
  },

  // ========== CONSTRUCTION MISSIONS ==========
  {
    id: 'mission-const-001',
    title: 'Skilled Trades Apprenticeship Program',
    description: 'Launch 50-person apprenticeship program for HVAC, electrical, and plumbing trades to support Montgomery\'s construction boom.',
    status: 'active',
    priority: 'critical',
    progress: 38,
    sectorId: 'construction',
    rewardPoints: 185,
    participantCount: 42,
    communityImpact: 'Create pathways to $55K+ careers for Montgomery residents, particularly in East Montgomery and West Montgomery neighborhoods.',
    tags: ['Apprenticeship', 'Skilled Trades', 'HVAC', 'Electrical', 'Career Pathways'],
    assignee: 'R. Davis, Workforce Development',
    dueDate: new Date('2026-08-31'),
    steps: [
      {
        id: 'const001-s1',
        order: 1,
        title: 'Partner with local contractors',
        description: 'Secure commitments from 15 construction companies to host apprentices.',
        completed: true,
        dueDate: new Date('2026-03-15'),
      },
      {
        id: 'const001-s2',
        order: 2,
        title: 'Register DOL apprenticeship programs',
        description: 'Complete federal apprenticeship registration for HVAC, electrical, and plumbing tracks.',
        completed: true,
        dueDate: new Date('2026-04-01'),
      },
      {
        id: 'const001-s3',
        order: 3,
        title: 'Recruit and screen candidates',
        description: 'Host info sessions and screen 100+ applicants for 50 apprentice slots.',
        completed: false,
        dueDate: new Date('2026-05-30'),
      },
      {
        id: 'const001-s4',
        order: 4,
        title: 'Launch first cohort',
        description: 'Start 50 apprentices in June with classroom instruction at Trenholm State.',
        completed: false,
        dueDate: new Date('2026-06-15'),
      },
    ],
    impactMetrics: [
      { label: 'Apprentices Enrolled', before: 0, after: 50, unit: 'apprentices' },
      { label: 'Skilled Trades Openings Filled', before: 8, after: 32, unit: 'positions' },
      { label: 'Avg Starting Wage', before: 32000, after: 42000, unit: '$/year' },
    ],
  },

  {
    id: 'mission-const-002',
    title: 'Safety Certification Blitz',
    description: 'Get 200 construction workers OSHA 10/30 certified to improve job site safety and meet contractor requirements.',
    status: 'active',
    priority: 'watch',
    progress: 72,
    sectorId: 'construction',
    rewardPoints: 110,
    participantCount: 38,
    communityImpact: 'Reduce workplace injuries and fatalities on construction sites across Montgomery.',
    tags: ['Safety', 'OSHA', 'Certification', 'Training'],
    assignee: 'C. Johnson, Safety Director',
    dueDate: new Date('2026-04-30'),
    steps: [
      {
        id: 'const002-s1',
        order: 1,
        title: 'Partner with OSHA training provider',
        description: 'Contract with authorized OSHA trainer for bulk training discount.',
        completed: true,
        dueDate: new Date('2026-02-15'),
      },
      {
        id: 'const002-s2',
        order: 2,
        title: 'Run 10 OSHA 10-hour classes',
        description: 'Offer evening and weekend classes to accommodate work schedules.',
        completed: true,
        dueDate: new Date('2026-03-30'),
      },
      {
        id: 'const002-s3',
        order: 3,
        title: 'Run 4 OSHA 30-hour classes',
        description: 'Target supervisors and foremen for advanced safety training.',
        completed: true,
        dueDate: new Date('2026-04-15'),
      },
      {
        id: 'const002-s4',
        order: 4,
        title: 'Track injury rate reduction',
        description: 'Measure 6-month injury rate for certified vs. non-certified workers.',
        completed: false,
        dueDate: new Date('2026-04-30'),
      },
    ],
    impactMetrics: [
      { label: 'Workers Certified', before: 45, after: 245, unit: 'certifications' },
      { label: 'Workplace Injuries', before: 28, after: 12, unit: 'incidents/quarter' },
      { label: 'Lost Time Incidents', before: 9, after: 3, unit: 'incidents/quarter' },
    ],
  },

  // ========== EDUCATION MISSIONS ==========
  {
    id: 'mission-edu-001',
    title: 'Special Education Teacher Pipeline',
    description: 'Address critical shortage of special education teachers in Montgomery Public Schools through recruitment and alternative certification pathways.',
    status: 'active',
    priority: 'critical',
    progress: 48,
    sectorId: 'education',
    rewardPoints: 175,
    participantCount: 26,
    communityImpact: 'Ensure every special needs student has access to certified special education instruction, improving educational outcomes and family support.',
    tags: ['Special Education', 'Teaching', 'Alternative Certification', 'Recruitment'],
    assignee: 'Dr. A. Wilson, MPS Superintendent',
    dueDate: new Date('2026-08-15'),
    steps: [
      {
        id: 'edu001-s1',
        order: 1,
        title: 'Launch alternative certification program',
        description: 'Partner with Auburn Montgomery for 1-year alternative SpEd certification track.',
        completed: true,
        dueDate: new Date('2026-03-01'),
      },
      {
        id: 'edu001-s2',
        order: 2,
        title: 'Recruit career-changers and paraprofessionals',
        description: 'Target existing classroom aides and career-changers with bachelor\'s degrees.',
        completed: true,
        dueDate: new Date('2026-04-15'),
      },
      {
        id: 'edu001-s3',
        order: 3,
        title: 'Offer tuition reimbursement',
        description: 'Cover 100% of certification costs ($8,500) for 3-year commitment to MPS.',
        completed: false,
        dueDate: new Date('2026-05-30'),
      },
      {
        id: 'edu001-s4',
        order: 4,
        title: 'Place first cohort in classrooms',
        description: 'Hire and place 18 newly certified SpEd teachers for fall 2026 semester.',
        completed: false,
        dueDate: new Date('2026-08-15'),
      },
    ],
    impactMetrics: [
      { label: 'SpEd Teacher Vacancies', before: 23, after: 5, unit: 'open positions' },
      { label: 'Student-Teacher Ratio (SpEd)', before: 18.5, after: 12.3, unit: 'students per teacher' },
      { label: 'IEP Compliance Rate', before: 78, after: 94, unit: '%' },
    ],
  },

  {
    id: 'mission-edu-002',
    title: 'Teacher Retention Incentive Program',
    description: 'Reduce teacher turnover from 16% to under 10% through retention bonuses, professional development stipends, and mentorship.',
    status: 'active',
    priority: 'watch',
    progress: 61,
    sectorId: 'education',
    rewardPoints: 140,
    participantCount: 34,
    communityImpact: 'More experienced teachers in classrooms, improving student achievement and reducing disruption from constant teacher turnover.',
    tags: ['Retention', 'Teacher Support', 'Professional Development', 'Mentorship'],
    assignee: 'K. Roberts, HR Director',
    dueDate: new Date('2026-06-30'),
    steps: [
      {
        id: 'edu002-s1',
        order: 1,
        title: 'Survey teachers on satisfaction drivers',
        description: 'Conduct anonymous survey to identify top reasons for departure.',
        completed: true,
        dueDate: new Date('2026-02-28'),
      },
      {
        id: 'edu002-s2',
        order: 2,
        title: 'Implement 3-year retention bonus',
        description: 'Offer $3,000 annual bonus for teachers who commit to 3 years in high-need schools.',
        completed: true,
        dueDate: new Date('2026-03-15'),
      },
      {
        id: 'edu002-s3',
        order: 3,
        title: 'Launch mentorship program',
        description: 'Pair new teachers with veteran mentors for first 2 years.',
        completed: true,
        dueDate: new Date('2026-04-30'),
      },
      {
        id: 'edu002-s4',
        order: 4,
        title: 'Provide professional development stipend',
        description: 'Offer $2,000 annual stipend for conferences, courses, or certifications.',
        completed: false,
        dueDate: new Date('2026-05-30'),
      },
    ],
    impactMetrics: [
      { label: 'Teacher Turnover Rate', before: 16, after: 9, unit: '%' },
      { label: 'Teacher Satisfaction Score', before: 62, after: 81, unit: '/100' },
      { label: 'Retention Bonus Participants', before: 0, after: 142, unit: 'teachers' },
    ],
  },

  // ========== LOGISTICS MISSIONS ==========
  {
    id: 'mission-log-001',
    title: 'CDL Driver Fast-Track Program',
    description: 'Train and certify 40 Class A CDL drivers to address critical shortage in logistics and municipal services.',
    status: 'active',
    priority: 'critical',
    progress: 52,
    sectorId: 'logistics',
    rewardPoints: 195,
    participantCount: 35,
    communityImpact: 'Ensure reliable trash collection, delivery of city services, and support for private sector logistics companies that employ hundreds of Montgomery residents.',
    tags: ['CDL', 'Driver Training', 'Fast-track', 'Logistics'],
    assignee: 'M. Davis, Fleet Manager',
    dueDate: new Date('2026-05-31'),
    steps: [
      {
        id: 'log001-s1',
        order: 1,
        title: 'Partner with CDL training school',
        description: 'Contract with Montgomery Truck Driving School for bulk training discount.',
        completed: true,
        dueDate: new Date('2026-03-01'),
      },
      {
        id: 'log001-s2',
        order: 2,
        title: 'Recruit 50 candidates',
        description: 'Target unemployed and underemployed residents, offer tuition assistance.',
        completed: true,
        dueDate: new Date('2026-03-20'),
      },
      {
        id: 'log001-s3',
        order: 3,
        title: 'Complete Class A CDL training',
        description: 'Run 4-week intensive program with classroom and behind-the-wheel training.',
        completed: true,
        dueDate: new Date('2026-04-30'),
      },
      {
        id: 'log001-s4',
        order: 4,
        title: 'Place graduates in jobs',
        description: 'Direct hiring pipeline with city waste management and private carriers.',
        completed: false,
        dueDate: new Date('2026-05-31'),
      },
    ],
    impactMetrics: [
      { label: 'CDL Drivers Certified', before: 0, after: 37, unit: 'drivers' },
      { label: 'City Fleet Vacancies', before: 12, after: 2, unit: 'open positions' },
      { label: 'Private Carrier Hires', before: 0, after: 25, unit: 'placements' },
    ],
  },

  // ========== FINANCE MISSIONS ==========
  {
    id: 'mission-fin-001',
    title: 'Finance Leadership Succession Planning',
    description: 'Develop 8 high-potential finance professionals to fill senior roles (Budget Director, Deputy CFO) within 18 months.',
    status: 'active',
    priority: 'watch',
    progress: 65,
    sectorId: 'finance',
    rewardPoints: 135,
    participantCount: 12,
    communityImpact: 'Ensure continuity in city financial management and budget planning, protecting taxpayer dollars and maintaining AAA bond rating.',
    tags: ['Succession Planning', 'Leadership', 'Finance', 'Mentorship'],
    assignee: 'CFO A. Johnson',
    dueDate: new Date('2026-07-31'),
    steps: [
      {
        id: 'fin001-s1',
        order: 1,
        title: 'Identify succession candidates',
        description: 'Use 360 reviews and performance data to select top 10 candidates.',
        completed: true,
        dueDate: new Date('2026-02-15'),
      },
      {
        id: 'fin001-s2',
        order: 2,
        title: 'Launch executive development program',
        description: 'Pair candidates with CFO mentors and assign stretch projects.',
        completed: true,
        dueDate: new Date('2026-03-30'),
      },
      {
        id: 'fin001-s3',
        order: 3,
        title: 'Fund CPA or CGFM certification',
        description: 'Cover exam costs and study materials for professional certifications.',
        completed: true,
        dueDate: new Date('2026-05-15'),
      },
      {
        id: 'fin001-s4',
        order: 4,
        title: 'Document succession readiness',
        description: 'Create succession matrix with readiness ratings for each senior role.',
        completed: false,
        dueDate: new Date('2026-07-31'),
      },
    ],
    impactMetrics: [
      { label: 'Succession-Ready Candidates', before: 2, after: 8, unit: 'candidates' },
      { label: 'Senior Role Coverage', before: 50, after: 95, unit: '%' },
      { label: 'Professional Certifications Earned', before: 3, after: 9, unit: 'certifications' },
    ],
  },

  // ========== RETAIL MISSIONS ==========
  {
    id: 'mission-ret-001',
    title: 'Retail Management Training Initiative',
    description: 'Upskill 30 retail supervisors into store manager roles to support Montgomery\'s retail expansion.',
    status: 'active',
    priority: 'stable',
    progress: 44,
    sectorId: 'retail',
    rewardPoints: 115,
    participantCount: 28,
    communityImpact: 'Create career advancement opportunities for frontline retail workers and support job growth at Eastdale Mall and the Shoppes at Eastchase.',
    tags: ['Retail', 'Management Training', 'Career Advancement', 'Leadership'],
    assignee: 'P. Martinez, Workforce Development',
    dueDate: new Date('2026-06-30'),
    steps: [
      {
        id: 'ret001-s1',
        order: 1,
        title: 'Partner with retail employers',
        description: 'Secure commitments from Target, Walmart, and local retailers.',
        completed: true,
        dueDate: new Date('2026-03-01'),
      },
      {
        id: 'ret001-s2',
        order: 2,
        title: 'Develop management curriculum',
        description: 'Create 8-week course covering P&L, scheduling, merchandising, and leadership.',
        completed: true,
        dueDate: new Date('2026-03-25'),
      },
      {
        id: 'ret001-s3',
        order: 3,
        title: 'Run first 2 cohorts',
        description: 'Train 30 supervisors in evening/weekend classes.',
        completed: false,
        dueDate: new Date('2026-05-30'),
      },
      {
        id: 'ret001-s4',
        order: 4,
        title: 'Track promotions to manager',
        description: 'Monitor promotion rate within 6 months of completion.',
        completed: false,
        dueDate: new Date('2026-06-30'),
      },
    ],
    impactMetrics: [
      { label: 'Supervisors Trained', before: 0, after: 30, unit: 'participants' },
      { label: 'Promotions to Manager', before: 0, after: 18, unit: 'promotions' },
      { label: 'Avg Wage Increase', before: 35000, after: 48000, unit: '$/year' },
    ],
  },
];
