export const sectorsSeed = [
  {
    id: 'public-safety',
    name: 'Public Safety',
    pulseScore: 75,
    status: 'critical',
    description: 'Police, fire, emergency medical services, and emergency management for the region.',
    employeeCount: 48200,
    openRolesCount: 312,
    kpis: [
      { label: 'Postings (7d)', value: 214, delta: 12, status: 'critical' },
      { label: 'WoW Change', value: '+12%', delta: 12, status: 'critical' },
      { label: 'Critical Roles', value: 8, delta: 3, status: 'critical' },
      { label: 'Unmapped Skills', value: 11, delta: 2, status: 'watch' },
    ],
  },
  {
    id: 'healthcare',
    name: 'Healthcare',
    pulseScore: 52,
    status: 'watch',
    description: 'Hospitals, clinics, nursing facilities, and allied health services.',
    employeeCount: 124500,
    openRolesCount: 589,
    kpis: [
      { label: 'Postings (7d)', value: 412, delta: -8, status: 'watch' },
      { label: 'WoW Change', value: '-8%', delta: -8, status: 'watch' },
      { label: 'Critical Roles', value: 5, delta: 1, status: 'watch' },
      { label: 'Unmapped Skills', value: 7, delta: -1, status: 'stable' },
    ],
  },
  {
    id: 'technology',
    name: 'Technology',
    pulseScore: 78,
    status: 'stable',
    description: 'Software, IT services, cybersecurity, and data infrastructure companies.',
    employeeCount: 89300,
    openRolesCount: 203,
    kpis: [
      { label: 'Postings (7d)', value: 156, delta: 4, status: 'stable' },
      { label: 'WoW Change', value: '+4%', delta: 4, status: 'stable' },
      { label: 'Critical Roles', value: 2, delta: -1, status: 'stable' },
      { label: 'Unmapped Skills', value: 4, delta: 0, status: 'stable' },
    ],
  },
  {
    id: 'construction',
    name: 'Construction',
    pulseScore: 65,
    status: 'watch',
    description: 'Residential, commercial, and infrastructure construction and skilled trades.',
    employeeCount: 67100,
    openRolesCount: 441,
    kpis: [
      { label: 'Postings (7d)', value: 298, delta: 9, status: 'watch' },
      { label: 'WoW Change', value: '+9%', delta: 9, status: 'watch' },
      { label: 'Critical Roles', value: 4, delta: 2, status: 'watch' },
      { label: 'Unmapped Skills', value: 8, delta: 3, status: 'critical' },
    ],
  },
  {
    id: 'education',
    name: 'Education',
    pulseScore: 61,
    status: 'stable',
    description: 'K-12 schools, community colleges, universities, and vocational training providers.',
    employeeCount: 95400,
    openRolesCount: 178,
    kpis: [
      { label: 'Postings (7d)', value: 124, delta: 2, status: 'stable' },
      { label: 'WoW Change', value: '+2%', delta: 2, status: 'stable' },
      { label: 'Critical Roles', value: 2, delta: 0, status: 'stable' },
      { label: 'Unmapped Skills', value: 3, delta: -1, status: 'stable' },
    ],
  },
  {
    id: 'logistics',
    name: 'Logistics',
    pulseScore: 80,
    status: 'critical',
    description: 'Warehousing, freight, transportation, and last-mile delivery operations.',
    employeeCount: 73800,
    openRolesCount: 527,
    kpis: [
      { label: 'Postings (7d)', value: 348, delta: 18, status: 'critical' },
      { label: 'WoW Change', value: '+18%', delta: 18, status: 'critical' },
      { label: 'Critical Roles', value: 6, delta: 4, status: 'critical' },
      { label: 'Unmapped Skills', value: 12, delta: 5, status: 'critical' },
    ],
  },
  {
    id: 'retail',
    name: 'Retail & Hospitality',
    pulseScore: 48,
    status: 'watch',
    description: 'Retail stores, restaurants, hotels, and hospitality services.',
    employeeCount: 156800,
    openRolesCount: 789,
    kpis: [
      { label: 'Postings (7d)', value: 524, delta: -5, status: 'watch' },
      { label: 'WoW Change', value: '-5%', delta: -5, status: 'watch' },
      { label: 'Critical Roles', value: 3, delta: 0, status: 'watch' },
      { label: 'Unmapped Skills', value: 6, delta: 1, status: 'stable' },
    ],
  },
  {
    id: 'finance',
    name: 'Finance & Professional Services',
    pulseScore: 55,
    status: 'stable',
    description: 'Banking, insurance, accounting, consulting, and legal services.',
    employeeCount: 78900,
    openRolesCount: 234,
    kpis: [
      { label: 'Postings (7d)', value: 168, delta: 3, status: 'stable' },
      { label: 'WoW Change', value: '+3%', delta: 3, status: 'stable' },
      { label: 'Critical Roles', value: 1, delta: 0, status: 'stable' },
      { label: 'Unmapped Skills', value: 2, delta: 0, status: 'stable' },
    ],
  },
];
