export const BENEFITS_CATALOG = [
  {
    id: 'app-priority',
    title: 'Priority candidacy',
    description: 'Get your application highlighted for partner employer roles in Montgomery.',
    category: 'application',
    costPoints: 150,
    eligibility: { minPoints: 100, minLevel: 2 },
    type: 'redeemable',
  },
  {
    id: 'app-fast-lane',
    title: 'Fast-lane triage',
    description: 'Priority screening for selected city and partner positions.',
    category: 'application',
    costPoints: 250,
    eligibility: { minPoints: 200, minLevel: 3 },
    type: 'redeemable',
  },
  {
    id: 'skills-course',
    title: 'Free training course voucher',
    description: 'Access one sponsored course from our training partners.',
    category: 'skills',
    costPoints: 100,
    eligibility: { minPoints: 50 },
    type: 'redeemable',
  },
  {
    id: 'skills-cert',
    title: 'Certification voucher',
    description: 'Subsidized certification exam for in-demand skills.',
    category: 'skills',
    costPoints: 300,
    eligibility: { minPoints: 200, minLevel: 4 },
    type: 'redeemable',
  },
  {
    id: 'contrib-badge',
    title: 'City Contributor badge',
    description: 'Exclusive badge for active workforce contributors.',
    category: 'contribution',
    costPoints: 0,
    eligibility: { minPoints: 500 },
    type: 'unlockable',
  },
  {
    id: 'contrib-playbook',
    title: 'Premium playbook access',
    description: 'Unlock advanced playbooks and mentorship resources.',
    category: 'contribution',
    costPoints: 200,
    eligibility: { minPoints: 150, requiredBadges: ['playbook-curator'] },
    type: 'redeemable',
  },
];
